### PR TITLE
fix: top-level spacing

### LINKED ISSUE #1748: formatter - top-level exprs not handled correctly
The formatter makes some assumptions about what types of expressions can be top-level. These assumptions are wrong. For example this code is valid  but handled incorrectly:

```
(define-map ns
  uint
  bool
)
(let ((x (+ u1 u1)))
  (map-insert ns x true)
)(define-public (get-value)
  (ok (map-get? ns u2))
)
```

1) Fix the underlying assumptions to make the above clarity formatted as:

```
(define-map ns uint bool)
(let ((x (+ u1 u1)))
  (map-insert ns x true)
)

(define-public (get-value)
  (ok (map-get? ns u2))
)
```

2) The `define-map` should be on 1 line

### PR DESCRIPTION
**Pull request by tippenein**
fix #1748

### CODE REVIEW

File: components/clarinet-format/src/formatter/mod.rs [hunk 1]
```diff
@@ -1405,6 +1412,19 @@ mod tests_formatter {
...
     }
 
+    #[test]
+    fn top_level_exprs() {
+        let src = r#"(let ((x (+ u1 u1)))
+  (map-insert ns x true)
+)
+(define-public (get-value)
+  (ok (map-get? ns u2))
+)
```
Comment (hugocaillard) [inline components/clarinet-format/src/formatter/mod.rs:1422]: Shouldn't it be
```clarity
(let ((x (+ u1 u1)))
  (map-insert ns x true)
)

(define-public (get-value)
  (ok (map-get? ns u2))
)

```

With an extra new-line before define-public?

Comment (tippenein) [reply components/clarinet-format/src/formatter/mod.rs:1422]: That is part of this issue: https://github.com/hirosystems/clarinet/issues/1769

The problem there was the top-comments get in the way of easily new-lining define- functions

**Review by hugocaillard — APPROVED** [review]
lgtm
