### PR TITLE
fix: list formatting breakage

### LINKED ISSUE #1799: Formatter breaks code after comments
**Describe the bug**
After formatting https://github.com/citycoins/protocol/blob/a6e79965b4e5ef5b8c6c04a11b4858120a48789b/contracts/proposals/ccip012-bootstrap.clar#L18 
the resulting clarity code is not valid anymore.

Using clarinet 3.0.1

Similar for https://github.com/citycoins/protocol/blob/63e2128c770b6ae82786582d01719514339e8d11/contracts/proposals/ccip016-missed-payouts.clar#L28

**To Reproduce**
1. Checkout out https://github.com/citycoins/protocol
2. Run `clarinet check`
3. Run `clarinet format --in-place`
4. Run `clarinet check`
5. See error

**Expected behavior**
Code remains valid.

### PR DESCRIPTION
**Pull request by tippenein**
- closes #1799 

- [x] fix inline comment newline issue
- [x] fix comment as item of a list
- [x] actually hand `format_list` for ListCons

This fixes the breakage in citycoins protocol contracts

Screenshot 2025-05-12 at 11 52 28 AM

### CODE REVIEW

File: components/clarinet-format/src/formatter/mod.rs [hunk 1]
```diff
@@ -941,7 +1020,7 @@ impl<'a> Aggregator<'a> {
                 _ => value.to_string(),
             },
             PreSymbolicExpressionType::List(ref items) => {
-                self.format_list(items, previous_indentation)
+                self.display_list(items, previous_indentation)
```
Comment (tippenein) [inline components/clarinet-format/src/formatter/mod.rs:1023]: this is nasty duplication but if we fall into the `display_pse` branch we want to format it like before. If the atom is a `ListCons` we use the new `format_list`

File: components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar [hunk 2]
```diff
@@ -264,7 +264,8 @@
         index: uint,
       },
       remaining: uint,
-      txins: (list 8 {
+      txins: (list 8
+        {
```
Comment (hugocaillard) [inline components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar:268]: not sure I follow this change.
If this `}` is on a new line, I think the indentation level shold be increased for the next lines.
And the matching `}` should be on the same indentation level

```clarity
      txins: (list 8
        {
          outpoint: {
            hash: (buff 32),
            index: uint,
          },
          scriptSig: (buff 256), ;; just big enough to hold a 2-of-3 multisig script
          sequence: uint,
        }
      ),
```

**Review by hugocaillard — APPROVED** [review]
I think what's the PR is trying to fix is looking good.

I left a questions regarding a side effect of theses changes in clarity-bitcoin.clar

File: components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar (hunk 2 above)
Comment (tippenein) [reply components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar:268]: Good catch. I believe this is because there's a difference between checking spans (list breaking on max lines) and the original place the opening bracket would have been 
```
(list 8 {
  ...
})
```

So, the list gets broken up onto multiple lines and the closing parens are still under the impression the `(` and `{` were opened on the same line.. Tricky, but i've made an issue [here](https://github.com/hirosystems/clarinet/issues/1810)
