### PR TITLE
Fix: preserve inner expr newlines (#1790)

### LINKED ISSUE #1790: preserve newlines within expressions
Formatter still removes extra new lines within functions. For example, in this snippet, the new line before `(ok)` is removed:

```clarity
(define-public (increment)
  (begin
    (try! (stx-transfer? (var-get cost) tx-sender (var-get contract-owner)))

    (ok (var-set count (+ (var-get count) u1)))
  )
)
```

### PR DESCRIPTION
**Pull request by tippenein**
- fixes #1790

### CODE REVIEW

File: components/clarinet-format/src/formatter/mod.rs [hunk 1]
```diff
@@ -1437,6 +1484,19 @@ mod tests_formatter {
...
     #[test]
+    fn test_preserve_newlines_inner_function() {
+        let src = r#"(define-public (increment)
+  (begin
+    (try! (stx-transfer? (var-get cost) tx-sender (var-get contract-owner)))
+
+    (ok (var-set count (+ (var-get count) u1)))
+  )
+)
+"#;
```
Comment (jbencin) [inline components/clarinet-format/src/formatter/mod.rs]: We've started using the `indoc` crate in some of the other components to keep multiline strings readable and indented with the rest of the code:

```suggestion
        let src = indoc!(r#"
          define-public (increment)
            (begin
              (try! (stx-transfer? (var-get cost) tx-sender (var-get contract-owner)))
              (ok (var-set count (+ (var-get count) u1)))
            )
          )"#;
```

You can add the workspace version in Cargo.toml:

```toml
indoc = { workspace = true }
```

File: components/clarinet-format/src/formatter/mod.rs [hunk 2]
```diff
@@ -1331,6 +1367,17 @@ fn chars_since_last_newline(acc: &str) -> usize {
     }
 }
 
+// Helper to insert at most one blank line if there are blank lines between two expressions
+fn push_blank_lines(acc: &mut String, prev_end_line: u32, curr_start_line: u32) {
+    if prev_end_line > 0 && curr_start_line > 0 && curr_start_line > prev_end_line {
```
Comment (jbencin) [inline components/clarinet-format/src/formatter/mod.rs]: I could be wrong, but it looks like you're using `0` to represent the absence of start_line/end_line here. In Rust you should do this with an `Option<u32>` instead.

Comment (tippenein) [reply components/clarinet-format/src/formatter/mod.rs]: There wouldn't be an absence of start_line since it's initially populated from the current `span`

File: components/clarinet-format/src/formatter/mod.rs (hunk 1 above)
Comment (tippenein) [reply components/clarinet-format/src/formatter/mod.rs]: This is what rustfmt does with formatting indoc ☹️ 

```
    fn intact_comment_spacing() {
        let src = indoc!(
            r#"
          ;; (define-read-only (has-access)
          ;;   (begin
          ;;     (ok true)
          ;;   )
          ;; )"#
        );
        let result = format_with_default(&String::from(src));
        assert_eq!(src, result);
```

Comment (tippenein) [reply components/clarinet-format/src/formatter/mod.rs:1495]: Made it a separate issue for now. 
https://github.com/hirosystems/clarinet/issues/1891

File: components/clarinet-format/src/formatter/mod.rs (hunk 2 above)
Comment (jbencin) [reply components/clarinet-format/src/formatter/mod.rs]: What about end_line? It's just when you see this sort of pattern in Rust code (comparing an integer type to `0`), it usually means you could be using an `Option` type instead

File: components/clarinet-format/tests/golden.rs [hunk 3]
```diff
@@ -61,6 +61,7 @@ fn test_irl_contracts() {
             let src = fs::read_to_string(&path).expect("Failed to read source file");
 
             let file_name = path.file_name().expect("Failed to get file name");
+            println!("file: {file_name:?}");
```
Comment (jbencin) [inline components/clarinet-format/tests/golden.rs:64]: Is this a debug print that should be removed?

Comment (tippenein) [reply components/clarinet-format/tests/golden.rs:64]: this is useful to have when testing because if the golden test fails you want to know which file it failed on

File: components/clarinet-format/src/formatter/mod.rs (hunk 2 above)
Comment (tippenein) [reply components/clarinet-format/src/formatter/mod.rs]: Changed it to Option and removed the extra `> 0`  checks. Seems like they weren't needed 👍

**Review by jbencin — APPROVED** [review]
